apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ex-aao-app
  name: ex-aao-app
  namespace: amq-710-playground
spec:
  endpoints:
    - interval: 30s
      port: wconsj-.*
  podTargetLabels:
    - ActiveMQArtemis
    - application
  selector:
    matchLabels:
      app: ex-aao-app
  jobLabel: ActiveMQArtemis
