apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: amq-monitoring-rules
  namespace: amq-710-playground
spec: 
  groups: 
    - name: amq-apps
      rules:
        - alert: AmqPodCrashLooping
          annotations:
            description: >-
              Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{
              $labels.container }}) is in waiting state (reason:
              "CrashLoopBackOff").
            summary: Pod is crash looping.
          expr: >
            max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff",
            namespace=~"(amq-.*)",job="kube-state-metrics"}[5m])
            >= 1
          for: 5m
          labels:
            severity: warning
        - alert: AmqPodNotReady
          annotations:
            description: >-
              Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a
              non-ready state for longer than 5 minutes.
            summary: Pod has been in a non-ready state for more than 5 minutes.
          expr: |
            sum by (namespace, pod) (
              max by(namespace, pod) (
                kube_pod_status_phase{namespace=~"(amq-.*)",job="kube-state-metrics", phase=~"Pending|Unknown"}
              ) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (
                1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})
              )
            ) > 0
          for: 5m
          labels:
            severity: warning
        - alert: AmqDeploymentGenerationMismatch
          annotations:
            description: >-
              Deployment generation for {{ $labels.namespace }}/{{
              $labels.deployment }} does not match, this indicates that the
              Deployment has failed but has not been rolled back.
            summary: Deployment generation mismatch due to possible roll-back
          expr: >
            kube_deployment_status_observed_generation{namespace=~"(amq-.*)",job="kube-state-metrics"}
              !=
            kube_deployment_metadata_generation{namespace=~"(amq-.*)",job="kube-state-metrics"}
          for: 15m
          labels:
            severity: warning
        - alert: AmqStatefulSetReplicasMismatch
          annotations:
            description: >-
              StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has
              not matched the expected number of replicas for longer than 15
              minutes.
            summary: Deployment has not matched the expected number of replicas.
          expr: |
            (
              kube_statefulset_status_replicas_ready{namespace=~"(amq-.*)",job="kube-state-metrics"}
                !=
              kube_statefulset_status_replicas{namespace=~"(amq-.*)",job="kube-state-metrics"}
            ) and (
              changes(kube_statefulset_status_replicas_updated{namespace=~"(amq-.*)",job="kube-state-metrics"}[10m])
                ==
              0
            )
          for: 15m
          labels:
            severity: warning
        - alert: AmqStatefulSetGenerationMismatch
          annotations:
            description: >-
              StatefulSet generation for {{ $labels.namespace }}/{{
              $labels.statefulset }} does not match, this indicates that the
              StatefulSet has failed but has not been rolled back.
            summary: StatefulSet generation mismatch due to possible roll-back
          expr: >
            kube_statefulset_status_observed_generation{namespace=~"(amq-.*)",job="kube-state-metrics"}
              !=
            kube_statefulset_metadata_generation{namespace=~"(amq-.*)",job="kube-state-metrics"}
          for: 15m
          labels:
            severity: warning
        - alert: AmqStatefulSetUpdateNotRolledOut
          annotations:
            description: >-
              StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }}
              update has not been rolled out.
            summary: StatefulSet update has not been rolled out.
          expr: |
            (
              max without (revision) (
                kube_statefulset_status_current_revision{namespace=~"(amq-.*)",job="kube-state-metrics"}
                  unless
                kube_statefulset_status_update_revision{namespace=~"(amq-.*)",job="kube-state-metrics"}
              )
                *
              (
                kube_statefulset_replicas{namespace=~"(amq-.*)",job="kube-state-metrics"}
                  !=
                kube_statefulset_status_replicas_updated{namespace=~"(amq-.*)",job="kube-state-metrics"}
              )
            )  and (
              changes(kube_statefulset_status_replicas_updated{namespace=~"(amq-.*)",job="kube-state-metrics"}[5m])
                ==
              0
            )
          for: 15m
          labels:
            severity: warning
        - alert: ArtemisMessageCountSum
          expr: sum by (pod) (artemis_message_count) > 0
          for: 1m
          labels:
            # namespace is automatically added
            severity: warning
            app: amq
          annotations:
            summary: Total message count is high
            description: Broker {{ $labels.pod }} - Total message count is high
            message: Total message count is {{ $value }}
        - alert: ArtemisMessageCountExpiryOrDLQ
          expr: artemis_message_count{queue=~'ExpiryQueue|DLQ'} > 0
          labels:
            severity: critical
            app: amq
          annotations:
            summary: Messages on {{ $labels.queue }} queue
            description: Broker {{ $labels.pod }} - Messages on {{ $labels.queue }}
            message: Messages count on {{ $labels.queue }} is {{ $value }}
